# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{graster}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jedediah Smith", "Joshua Hull"]
  s.date = %q{2009-12-18}
  s.description = %q{G Raster!}
  s.email = %q{joshbuddy@gmail.com}
  s.executables = ["graster", "gtile"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/graster",
    "bin/gtile",
    "lib/graster.rb",
    "lib/graster/gcode_file.rb",
    "lib/graster/gmask_file.rb",
    "lib/graster/image.rb",
    "lib/graster/runner.rb"
  ]
  s.homepage = %q{http://github.com/joshbuddy/graster}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{graster}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{G Raster!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rmagick>, [">= 0"])
    else
      s.add_dependency(%q<rmagick>, [">= 0"])
    end
  else
    s.add_dependency(%q<rmagick>, [">= 0"])
  end
end

